spring.application.name=golds-gym-backend
# Automatically updates your database tables when the application boots up online
spring.datasource.url=${JDBC_DATABASE_URL}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
